# Generated by Django 3.1.3 on 2024-08-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20240801_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='GUEST', max_length=30),
        ),
    ]
